-- 02_create_tables.sql -

-- Dimension Date (structure EXACTE requise + enrichissements)
CREATE TABLE dwh.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL,
    year_number INTEGER NOT NULL,
    month_number INTEGER NOT NULL,
    month_name VARCHAR(20),
    quarter_number INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    week_number INTEGER,        -- Pour les analyses hebdomadaires
    day_name VARCHAR(10),       -- Nom du jour par exemple (Lundi, Mardi...)
    is_holiday BOOLEAN          -- Jour férié ou non
);

-- Dimension Customer (SCD Type 2 + enrichissements)
CREATE TABLE dwh.dim_customer (
    customer_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_business_key INTEGER NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(150),
    gender VARCHAR(10),
    country VARCHAR(50),
    city VARCHAR(100),
    birth_date DATE,
    -- Colonnes SCD Type 2
    valid_from DATE NOT NULL DEFAULT '1900-01-01',
    valid_to DATE,
    is_current BOOLEAN NOT NULL DEFAULT TRUE
);

-- Dimension Store (SCD Type 1 + enrichissements)
CREATE TABLE dwh.dim_store (
    store_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_business_key INTEGER NOT NULL UNIQUE,
    store_name VARCHAR(200),
    city VARCHAR(100),
    country VARCHAR(50),
    region VARCHAR(50),
    store_type VARCHAR(50),     
    opening_date DATE
);

-- Dimension Product (SCD Type 2 + enrichissements)
CREATE TABLE dwh.dim_product (
    product_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_business_key INTEGER NOT NULL,
    product_name VARCHAR(300),
    brand VARCHAR(100),
    category VARCHAR(100),
    subcategory VARCHAR(100),
    catalog_price DECIMAL(10,2), 
    -- Colonnes SCD Type 2
    valid_from DATE NOT NULL DEFAULT '1900-01-01',
    valid_to DATE,
    is_current BOOLEAN NOT NULL DEFAULT TRUE
);

-- Fact Sales (structure EXACTE requise + contraintes supplémentaires)
CREATE TABLE dwh.fact_sales (
    sales_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key INTEGER NOT NULL,
    customer_key INTEGER NOT NULL,
    store_key INTEGER NOT NULL,
    product_key INTEGER NOT NULL,
    transaction_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    discount_amount DECIMAL(10,2) DEFAULT 0,
    
    CONSTRAINT fk_sales_date FOREIGN KEY (date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_key) REFERENCES dwh.dim_customer(customer_key),
    CONSTRAINT fk_sales_store FOREIGN KEY (store_key) REFERENCES dwh.dim_store(store_key),
    CONSTRAINT fk_sales_product FOREIGN KEY (product_key) REFERENCES dwh.dim_product(product_key),
    CONSTRAINT uq_transaction UNIQUE (transaction_id, product_key) -- éviter doublons
);

-- Ce sont les indexes pour optimiser les analyses
CREATE INDEX idx_fact_sales_date ON dwh.fact_sales(date_key);
CREATE INDEX idx_fact_sales_customer ON dwh.fact_sales(customer_key);
CREATE INDEX idx_fact_sales_store ON dwh.fact_sales(store_key);
CREATE INDEX idx_fact_sales_product ON dwh.fact_sales(product_key);
CREATE INDEX idx_fact_sales_transaction ON dwh.fact_sales(transaction_id);

-- Indexes supplémentaires sur dimensions
CREATE INDEX idx_customer_country ON dwh.dim_customer(country);
CREATE INDEX idx_store_region ON dwh.dim_store(region);
CREATE INDEX idx_product_category ON dwh.dim_product(category);

-- Indexes partiels pour gérer le SCD Type 2, ça garantit que la business_key est unique seulement pour les lignes actives (is_current = TRUE)
CREATE UNIQUE INDEX uq_dim_customer_bk_current
    ON dwh.dim_customer(customer_business_key)
    WHERE is_current = TRUE;

CREATE UNIQUE INDEX uq_dim_product_bk_current
    ON dwh.dim_product(product_business_key)
    WHERE is_current = TRUE;
